### ISSUE TITLE
Steps to run it in windows machine

### ISSUE THREAD

**Issue by Mamta92** [pieper/SlicerWeb#3]
Hi @pieper , @davetchen, @blezek 

We cloned this and tried to run on our windows machine.
1) After cloning, we tried running ***pip install -r SETUP.txt***. We got an error - ERROR: Invalid requirement: 'Connecting to the AWS Slicer server' (from line 1 of SETUP.txt)
2) Running python webserver.py from /WebServer gave an error - ImportError: cannot import name 'vtk' from '__main__' (D:\SlicerWeb\WebServer\webserver.py)

Could you please help us with the exact steps to be followed right from the start after cloning to successfully launch it on localhost:80? Any more help on 'This module can now be run from any slicer 4.2 binary download' ? 
The folder structure looks a bit different as the ones's mentioned in Readme.

Thanks!!

**Comment by pieper** [comment]
Hi @Mamta92 - 

This code is made to be run from inside of a running instance of [3D Slicer](https://slicer.org).

You can use the command line in the from the readme `./path/to/Slicer --additional-module-paths path/to/SlicerWeb/WebServer` which might look like this on a windows machine with the current Slicer release: `"c:\Users\pieper\AppData\Local\NA-MIC\Slicer 4.11.20210226" --additional-module-paths c:\pieper\SlicerWeb\WebServer` (replace `pieper` with your login).  

Then you need to select the WebServer module from the Servers category of the Module menu.

There are a few demo buttons there.  This is still basically a prototype, but it works pretty well and I've been looking for places where it might solve problems in a useful way.

I'm going to close this issue but feel free to reopen if you have further questions.
